server:
  port: 8485
  servlet:
    context-path: /bigdata
queueName: publish.queue
topicName: publish.topic
spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static/,classpath:/templates/
#  rabbitmq:
#    host: 192.168.1.128
#    port: 5672
#    username: admin
#    password: admin
#    publisher-confirms: true
#    virtual-host:
#    template:
#      mandatory: true
#    listener:
#      type: simple
#      simple:
#        acknowledge-mode: manual
#        concurrency: 5
#        max-concurrency: 100
#        default-requeue-rejected: true
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 5000
    database: 0
    

#jasypt加密的密匙
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7

mybatis-plus:
  mapper-locations: classpath:/static/mapper/*.xml #@Bean(name = "sqlSessionFactory")已配置
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
#日志.
logging:
  path: ./logs
  file:
    max-size: 50MB
  level:
    root: info

#zookeeper
zk:
  url: 192.168.1.128:2181

elasticsearch:
  ip: 192.168.1.128
  port: 9200
  size: 100